<a href="https://colab.research.google.com/github/patilshreyas22/DSBDA-Practicals/blob/main/practical6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on
iris.csvdataset.
2. Compute Confusion matrix to find TP,

In [29]:
import pandas as pd

import numpy as np

from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score , precision_score , recall_score , confusion_matrix

from sklearn.preprocessing import MinMaxScaler

In [30]:
df = pd.read_csv("/content/Iris.csv")

In [31]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [32]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [33]:
x = df[['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

y = df['Species']

In [37]:
scaler = MinMaxScaler()

x_scaled = scaler.fit_transform(x)

x_scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.01342282, 0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.02013423, 0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.02684564, 0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.03355705, 0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.04697987, 0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.05369128, 0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.08724832, 0.        , 0.41666667, 0.01694915, 0.        ],
       [0.09395973, 0.41666667, 0.

In [38]:
x_train , x_test , y_train , y_test = train_test_split(x_scaled , y , test_size = 0.25 , random_state = 25)

In [39]:
model = GaussianNB()

model.fit(x_train , y_train)

GaussianNB()

In [40]:
y_pred = model.predict(x_test)

In [42]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa'], dtype='<U15')

In [43]:
y_test

28         Iris-setosa
72     Iris-versicolor
70     Iris-versicolor
85     Iris-versicolor
128     Iris-virginica
65     Iris-versicolor
127     Iris-virginica
42         Iris-setosa
81     Iris-versicolor
93     Iris-versicolor
21         Iris-setosa
31         Iris-setosa
26         Iris-setosa
133     Iris-virginica
6          Iris-setosa
58     Iris-versicolor
125     Iris-virginica
139     Iris-virginica
64     Iris-versicolor
94     Iris-versicolor
79     Iris-versicolor
99     Iris-versicolor
66     Iris-versicolor
20         Iris-setosa
34         Iris-setosa
117     Iris-virginica
69     Iris-versicolor
122     Iris-virginica
120     Iris-virginica
41         Iris-setosa
54     Iris-versicolor
113     Iris-virginica
135     Iris-virginica
4          Iris-setosa
115     Iris-virginica
52     Iris-versicolor
68     Iris-versicolor
40         Iris-setosa
Name: Species, dtype: object

In [44]:
a = accuracy_score(y_test , y_pred)

In [51]:
e = 1 - a

In [52]:
a

1.0

In [53]:
e

0.0

In [54]:
cm = confusion_matrix(y_test , y_pred)

In [55]:
cm

array([[11,  0,  0],
       [ 0, 16,  0],
       [ 0,  0, 11]])

In [65]:
df['Species'].sum()

'Iris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-setosaIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolorIris-versicolo

In [66]:
lbs = ['Iris-setosa' , 'Iris-virginica' , 'Iris-versicolor']

In [67]:
print(confusion_matrix(y_test , y_pred , labels = lbs))

[[11  0  0]
 [ 0 11  0]
 [ 0  0 16]]
